export type UserRole = 'nanny' | 'owner' | 'admin' | 'parent'
export type VerificationStatus = 'pending' | 'verified' | 'expired' | 'failed'
export type DocumentType = 'criminal_record' | 'image_usage_consent' | 'medical_book' | 'personal_data_consent'
export type TrainingStage = 'stage_1' | 'stage_2' | 'stage_3' | 'stage_4' | 'stage_5'
export type ParentStatus = 'default' | 'star' | 'diamond'