// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ptwwhlsewbmhwsvzdpww.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB0d3dobHNld2JtaHdzdnpkcHd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQyMTM1MDQsImV4cCI6MjA0OTc4OTUwNH0.NmYbm0LbJ2uKrL7ImdQVFcN7GIhrh5Ivh-7QPsOkKGE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);